FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY . /app
RUN mvn clean test

FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/target/site/jacoco /app/jacoco/

RUN npm install -g http-server

EXPOSE 8081

CMD ["http-server", "/app/jacoco", "-p", "8081"]